name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 3.1.0
homepage: https://github.com/haduyphuong/flare_flutter

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
